sudo: false
language: node_js
node_js:
  - node

os: osx

before_deploy:
  - ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
  - npm run prebuild
  - tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds" .

deploy:
  provider: releases
  draft: false
  prerelease: true
  api_key:
    secure: "tHpcEyO6pGOve2R9ssn7F8JmUyfECvOzqc+kBY4VVQW7BikgOFKu9yfSlvPfx3OtiifN4E5wYpZUla37COrhbxATRnkidh0GIcBAfS73tFYA+Il0OU0i2w12lpP6Z4ODb9TqKvLk0ZQcUZqiC9lKwX3LshLxps2My0NojA2qU50bxLVyhrYrXhDwPtthdqaWtDESXdRtnfWt/kHew5pFrSg9HbwF3Nj2TR2BzQtfpb/Ve4YjGEV5VXQ9vop2eursiUZtH4RxkkyliJDIxFCb6SxSFixuk4l+7yKzpo814gresLuNbREL7H6FtqZQcHPgZfQoU/zJjY6nqOslZ18ccTlg9jRpSgyH3akCqc6J8cueA2a0D+efRyfLWazkEy3Hw9ehket38kA2mWInUJij39pN3R+rQUL3CImm56ot6JuaiQoAu9GSLj6lwvkeXZXQzR57lBS0VkcBGLpH4nj1+gtCwRd6zHdxmzXbci2v5rjyduC5f+PBvLBvts7HXGt38VKyg3HAWaIqhLwNldlM/+/kiWFZhjU6EvAE1gMTv/VkByU89+Hw1v/m/KeNXwa7GuMWkygzBwHNJHHGoYpcV7pUbjghjrKLrAE5B9kKIb2MTtgVK/OwgRWm43mmKUxVpISLXM5ep3neDT6mjkDOG6vWFxznaJ5MO+fEtdH7++4="
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    node: 'node'
